### ISSUE TITLE
ModuleNotFoundError: No module named 'reid_sampler'

### ISSUE THREAD

**Issue by ppengtang** [layumi/Person-reID-triplet-loss#1]
Hi,

When I try to run the train_new.py, I meet the problem ModuleNotFoundError: No module named 'reid_sampler'.
Could you fix this?
Thanks.

**Comment by layumi** [comment]
Hi @ppengtang 
You may just comment this line.

**Comment by ppengtang** [comment]
This works.
Thank you.
