### ISSUE TITLE
evaluate re_reank.py doesn't show any results

### ISSUE THREAD

**Issue by UsamaI000** [layumi/Person-reID-triplet-loss#22]
Hi,
I am trying to run evaluate re_rank.py But it gives me no result. I am using Google Colab. This is the output I get when running the script.

calculate initial distance
tcmalloc: large alloc 1557413888 bytes == 0x22e2c000 @  0x7f8adef611e7 0x7f8adcac75e1 0x7f8adcb2bc78 0x7f8adcb2be24 0x7f8adcb2274c 0x7f8adcd5f28c 0x7f8adcbbec10 0x7f8adcbc355a 0x567193 0x59fe1e 0x7f8adcb174ed 0x50a47f 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x507f24 0x50b053 0x634dd2 0x634e87 0x63863f 0x6391e1 0x4b0dc0 0x7f8adeb5eb97 0x5b26fa
tcmalloc: large alloc 1823244288 bytes == 0x9243a000 @  0x7f8adef611e7 0x7f8adcac75e1 0x7f8adcb2bc78 0x7f8adcb2bd93 0x7f8adcbc9ea8 0x7f8adcbca704 0x7f8adcbca852 0x567193 0x59fe1e 0x7f8adcb174ed 0x50a47f 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50cfd6 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x507f24 0x50b053 0x634dd2 0x634e87 0x63863f 0x6391e1 0x4b0dc0 0x7f8adeb5eb97 0x5b26fa
tcmalloc: large alloc 2134441984 bytes == 0xfef02000 @  0x7f8adef611e7 0x7f8adcac75e1 0x7f8adcb2bc78 0x7f8adcb2bd93 0x7f8adcbc9ea8 0x7f8adcbca704 0x7f8adcbca852 0x567193 0x59fe1e 0x7f8adcb174ed 0x50a47f 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50cfd6 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x507f24 0x50b053 0x634dd2 0x634e87 0x63863f 0x6391e1 0x4b0dc0 0x7f8adeb5eb97 0x5b26fa
tcmalloc: large alloc 2134441984 bytes == 0x7fb70000 @  0x7f8adef611e7 0x7f8adcac75e1 0x7f8adcb2bc78 0x7f8adcb2bd93 0x7f8adcd24037 0x7f8adcd26492 0x7f8adcd2730e 0x5a4a0c 0x5a50d8 0x7f8adcbea06b 0x5a10c1 0x50d3a4 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x507f24 0x50b053 0x634dd2 0x634e87 0x63863f 0x6391e1 0x4b0dc0 0x7f8adeb5eb97 0x5b26fa
tcmalloc: large alloc 2134441984 bytes == 0x17e292000 @  0x7f8adef611e7 0x7f8adcac75e1 0x7f8adcb2bc78 0x7f8adcb2bd93 0x7f8adcd24037 0x7f8adcd26492 0x7f8adcd2730e 0x5a4a0c 0x5a50d8 0x7f8adcbea54b 0x59cb28 0x50cdb9 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x507f24 0x50b053 0x634dd2 0x634e87 0x63863f 0x6391e1 0x4b0dc0 0x7f8adeb5eb97 0x5b26fa
tcmalloc: large alloc 2134441984 bytes == 0x7fb70000 @  0x7f8adef611e7 0x7f8adcac75e1 0x7f8adcb2bc78 0x7f8adcb2bd93 0x7f8adcd24037 0x7f8adcd26492 0x7f8adcd2730e 0x5a4a0c 0x5a50d8 0x7f8adcbea06b 0x5a10c1 0x50d3a4 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x507f24 0x50b053 0x634dd2 0x634e87 0x63863f 0x6391e1 0x4b0dc0 0x7f8adeb5eb97 0x5b26fa
tcmalloc: large alloc 4268883968 bytes == 0x1fde7a000 @  0x7f8adef611e7 0x7f8adcac75e1 0x7f8adcb2bc78 0x7f8adcb2bd93 0x7f8adcb7769c 0x7f8adcb7b593 0x7f8adcbba0d6 0x567193 0x511341 0x507f24 0x509c50 0x50a64d 0x50cfd6 0x507f24 0x588e91 0x59fe1e 0x7f8adcb174ed 0x50a47f 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x507f24 0x50b053 0x634dd2 0x634e87
^C

**Comment by layumi** [comment]
@UsamaI000 
Sorry for the late response. It seems to be out of memory (cpu memory).
