### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by x3smileyxd** [layumi/Person-reID-triplet-loss#7]
Hi, when I run the code on Market1501 dataset using 'train only' I get this error, but when i run on Market1501 dataset using 'train all', Duke dataset using 'train only' and 'train all' I get no error.

I could not find which part went wrong. Please help. Thank you.

  File "/home/leeyh/Person-reID-triplet-loss/tripletfolder.py", line 47, in __getitem__
    pos_path = self._get_pos_sample(target, index)
  File "/home/leeyh/Person-reID-triplet-loss/tripletfolder.py", line 32, in _get_pos_sample
    t = i % (len(rand))
ZeroDivisionError: integer division or modulo by zero

**Comment by layumi** [comment]
Hi @x3smileyxd ,
Some classes only contain less than 2 images. 
If you put one image into the validation set, it may lead to 1 image for this class.

We can not sample a triplet input from this class.

**Comment by x3smileyxd** [comment]
Thank you so much. That solved the problem.
